apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: rest-api
  name: rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: rest-api
    spec:
      containers:
        - env:
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USER
          image: custom-node
          name: rest-api
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          volumeMounts:
            - mountPath: /src
              name: code
      restartPolicy: Always
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
